export const MASTER_LOGO: Record<string, string> = {
  애플: '/logos/AAPL.png',
  '아메리칸 익스프레스': '/logos/AXP.png',
  뱅크오브아메리카: '/logos/BAC.png',
  코카콜라: '/logos/KO.png',
  쉐브론: '/logos/CVX.png',
  월마트: '/logos/WMT.png',
  페니메이: '/logos/FNMA.png',
  맥도날드: '/logos/MCD.png',
  시어스: '/logos/SHLD.png',
  '에머슨 일렉트릭': '/logos/EMR.png',
  'IVV (S&P 500 ETF)': '/logos/IVV.png',
  'SPY (S&P 500 ETF)': '/logos/SPY.png',
  'IEMG (신흥국 ETF)': '/logos/IEMG.png',
  엔비디아: '/logos/NVDA.png',
  '프록터 앤 갬블': '/logos/PG.png',
  테슬라: '/logos/TSLA.png',
  '일라이 릴리': '/logos/LLY.png',
  레딧: '/logos/RDDT.png',
  알파벳: '/logos/GOOGL.png',
};
